### ISSUE TITLE
Citation / Reference for DecisionTree.jl

### ISSUE THREAD

**Issue by Hugemiler** [JuliaAI/DecisionTree.jl#193] opened 2022-10-30 20:05 UTC
I'm working on a paper where I used DecisionTree.jl as a major component of data analysis. However, I did not find a bibliographic reference for it, on the README or the Docstrings. It would be nice to have a DOI for it, and make it easily accessible.

**Comment by ablaom** [comment] 2022-10-31 02:00
Right. My suggestion would be to create a [Zenodo entry](https://zenodo.org) entry - that will give DT a DOI.  I am copying in the original author who is no longer a maintainer. 

@bensadeghi Are you okay with that? I think ideally you should arrange this - it's pretty easy (~30min of your time). Otherwise, can you please suggest appropriate authors? In particular, important contributors without substantial commits.

**Comment by bensadeghi** [comment] 2022-10-31 02:24
Hi @ablaom . Yes, this is just fine and needed. Sounds like you already have experience with Zenodo, so if you won't mind adding the entry, that would be great. 

In addition to the top 10 contributors (making sure to include the JuliaAI team), I would ask that the following folks be included as authors as well:

Kevin Squire - @kmsquire
Daniel C. Jones - @dcjones
Andreas Noack - @andreasnoack

Thanks in advance!

**Comment by ablaom** [comment] 2022-11-01 04:09
Okay, then the complete author list is below. A tick means author has confirmed they are happy to be included:

- [x] Ben Sadeghi @bensadeghi 
- [ ] Poom Chiarawongse @Eight1911 
- [ ] Kevin Squire - @kmsquire
- [ ] Daniel C. Jones - @dcjones
- [ ] Andreas Noack - @andreasnoack
- [ ] Cédric St-Jean @cstjean 
- [ ] ? @tchiarawongs 
- [ ] Rik Huijzer @rikhuijzer 
- [ ] Roland Schätzle @roland-KA 
- [ ] ? @salbert83 
- [ ] Ian Butterworth @IanButterworth 
- [x] Anthony Blaom @ablaom 
- [ ] Yu-Fong Peng @yufongpeng

If you are on this list and are happy to share "authorship" for the proposed Zenodo entry for DecisionTree.jl, **then please ping below to confirm**.  I aim to create the listing around November 10th 13:00 UTC. 

If you want an institution/company affiliation and/or ORCID id added, please add.

@tchiarawongs, @salbert83 I will need names in real life if you want inclusion. If you prefer, you can direct message me in the on Julia slack or Julia Discourse. My handle is @ablaom on both.

**Comment by rikhuijzer** [comment] 2022-11-01 10:57
👍

**Comment by roland-KA** [comment] 2022-11-01 11:20
👍

**Comment by yufongpeng** [comment] 2022-11-01 11:38
👍

**Comment by cstjean** [comment] 2022-11-01 12:53
👍

**Comment by IanButterworth** [comment] 2022-11-01 14:12
+1 (but I'm doing so mainly to not complicate your goal, as I've made a very small contribution here)

**Comment by ablaom** [comment] 2022-11-28 19:55
Closed as completed: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7359268.svg)](https://doi.org/10.5281/zenodo.7359268)

cc @Hugemiler

**Closed by ablaom** 2022-11-28 19:55 UTC

**Comment by roland-KA** [comment] 2022-11-28 20:10
Hi @ablaom ... just wondering: the names on the Zenodo page and the list above are a bit different 🤓🤔; is this by intention oder did something go wrong?

**Comment by ablaom** [comment] 2022-11-28 21:13
Right, I see that some names are missing: 

Andreas Noack, Roland Schätzle, Yu-Fong Peng

Certainly not intended. Thanks for flagging! I'll investigate.

**Comment by ablaom** [comment] 2022-11-28 21:19
Fixed.
